version: '3.5'

services:
  npm:
    build: ./
    working_dir: /opt/project/
    command: npm install
    volumes: 
       - .:/opt/project/
  bot:
    build: ./
    command: npm start
    environment:
      - DEBUG=*
  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    command: --init-file /data/application/init.sql --default-authentication-plugin=mysql_native_password
    volumes:
      - ./databaseCreation.sql:/data/application/init.sql
      - servant_db:/var/lib/mysql
    environment: 
      MYSQL_ROOT_PASSWORD: servant
      MYSQL_DATABASE: servant
      MYSQL_USER: dev
      MYSQL_PASSWORD: dev
volumes:
  servant_db: