name: UpdateProduction

on:
  workflow_dispatch:
  push:
    branches: 
      - master
  pull_request:
    branches: 
      - master

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
    - name: Run SSH command
      uses: garygrossgarten/github-action-ssh@v0.5.0
      with:
        command: cd ${{ secrets.REMOTE_PATH }} && ./update.sh
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        passphrase: ${{ secrets.PASSPHRASE }}
        privateKey: ${{ secrets.PRIVATE_KEY}}
